
apiVersion: v1
kind: Namespace
metadata:
  name: beta
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: beta
type: Opaque
data:
  # Base64 encoded values: paswrd -> cGFzd3Jk
  root-password: cGFzd3Jk
  db-user: cm9vdA==
  db-password: cGFzd3Jk
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: beta
  labels:
    name: mysql
spec:
  containers:
    - name: mysql
      image: mysql:5.6
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: beta
spec:
  selector:
    name: mysql
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-mysql
  namespace: beta
  labels:
    name: webapp-mysql
spec:
  selector:
    matchLabels:
      name: webapp-mysql
  template:
    metadata:
      name: webapp-mysql
      labels:
        name: webapp-mysql
    spec:
      containers:
        - name: webapp-mysql
          image: mmumshad/simple-webapp-mysql
          ports:
            - containerPort: 8080
          env:
            - name: DB_Host
              value: mysql-service
            - name: DB_User
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: db-user
            - name: DB_Password
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: db-password
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: beta
spec:
  type: NodePort
  selector:
    name: webapp-mysql
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30082
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: beta
spec:
  podSelector: {}
  policyTypes:
  - Ingress

